%This code takes the output from IPD_Cont_Source_3box_Model to generate a
%single figure that displays the NEEM and GISP2 derived gradients.

%Code generated by Ben Riddell-Young (January 2021)

%close all
clear all
%% First load NEEM and GISP2 gradient data

%NEEM Data
NEEM4box = load('NEEM4box.mat');
NEEM4box = NEEM4box.NEEM4box;
NEEMIPG = cell2mat(NEEM4box(1,1));
NEEMCH4 = cell2mat(NEEM4box(2,1));
NEEMWAISCH4 = cell2mat(NEEM4box(3,1));
NEEMNSource = cell2mat(NEEM4box(4,1));
NEEMTSource = cell2mat(NEEM4box(5,1));
NEEMSSource = cell2mat(NEEM4box(6,1));
NEEMCH4Smooth = cell2mat(NEEM4box(7,1));
NEEMWAISSmooth = cell2mat(NEEM4box(8,1));

%GISP2 Data
GISP24box = load('GISP24box.mat');
GISP24box = GISP24box.GISP24box;
GISP2IPG = cell2mat(GISP24box(1,1));
GISP2CH4 = cell2mat(GISP24box(2,1));
GISP2WAISCH4 = cell2mat(GISP24box(3,1));
GISP2NSource = cell2mat(GISP24box(4,1));
GISP2TSource = cell2mat(GISP24box(5,1));
GISP2SSource = cell2mat(GISP24box(6,1));
GISP2CH4Smooth = cell2mat(GISP24box(7,1));
GISP2WAISSmooth = cell2mat(GISP24box(8,1));

%Edit S Sources: Decrease to 12 Tg yr-1 for end of record to 14.5 kyr
%Define line of array where 14.5 kyr occurs
GISP214 = 68;
%GISP2SSourceL = GISP2SSource(1:GISP214,2);
%GISP2SSourceLAge = GISP2SSource(1:GISP214,1);
%GISP2SSourceH = GISP2SSource((GISP214+1):end,2)-3;
%GISP2SSourceHAge = GISP2SSource((GISP214+1):end,1);
%GISP2SSource = [GISP2SSourceLAge,GISP2SSourceL;GISP2SSourceHAge,GISP2SSourceH];
%% Define x lims and climate intervals

%Timing of DO events obtained from Rasmussen et al., 2014 GICC05 chronology
%Timing of Heinrich stadials obtained from chapman et al., 1999 on the GICC05 chronology

BAx = [14600 12800 12800 14600];
H1x = [18000 14600 14600 18000];
DOx = [23350 22900 22900 23350];
H2bx = [24000 23430 23430 24000];
H2ax = [25725 25100 25100 25725];

%% Load speleothem, MSL and Eland data

SL = csvread('Lambeck_2014b.csv',1,2);
SLC = csvread('Lambeck_2014_curve.csv',4,0);
SpelS = csvread('Botuvera_18O_speleothems.csv',99,0);
SpelN = csvread('Cheng_2016.csv',1,0);
SpelND = csvread('Dykoski_2005.csv',3,1);
Inso = csvread('Berger_1978_insolation.csv',2,0);
Eland = xlsread('Seltzer_Eland.xlsx');

%Define 95% confidence intervals
SLChigh = SLC(:,3) + 2 * SLC(:,4);
SLClow = SLC(:,3) - 2 * SLC(:,4);

%% Plot

f = figure(3);
% p = get(0, "MonitorPositions");
% f.Position = p(1, :); % second display
f.Position = [1833 -110 650 800];
hold on
set(gcf,'Color','w');
ax = gca;
ax.XColor = 'None';
ax.YColor = 'None';
clear ax

%Add shading for climate intervals
annotation("rectangle",[.319 .07 .022 .92],"FaceColor",[.3 .3 .3],'FaceAlpha',.1,'Color','none')
annotation("rectangle",[.288 .07 .028 .92],"FaceColor",[0 0.4470 0.7410],'FaceAlpha',.1,'Color','none')
annotation("rectangle",[.213 .07 .025 .92],"FaceColor",[0 0.4470 0.7410],'FaceAlpha',.1,'Color','none')
annotation("rectangle",[.565 .07 .15 .92],"FaceColor",[0 0.4470 0.7410],'FaceAlpha',.1,'Color','none')
annotation("rectangle",[.72 .07 .083 .92],"FaceColor",[.3 .3 .3],'FaceAlpha',.1,'Color','none')

%Plot IPD estimate:
box off
axes('Position',[.14, .79, .72, .2])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
hold on
%Plot NEEM data 
ha = jbfill(NEEMIPG(12:24,1)',(NEEMIPG(12:24,2)+2*NEEMIPG(12:24,3))',(NEEMIPG(12:24,2)-2*NEEMIPG(12:24,3))',[0.8500 0.3250 0.0980]);
hold on
plot(NEEMIPG(12:24,1),NEEMIPG(12:24,2),'k-','LineWidth',2);
hold on 
ha = jbfill(NEEMIPG(35:62,1)',(NEEMIPG(35:62,2)+2*NEEMIPG(35:62,3))',(NEEMIPG(35:62,2)-2*NEEMIPG(35:62,3))',[0.8500 0.3250 0.0980]);
hold on
plot(NEEMIPG(35:62,1),NEEMIPG(35:62,2),'k-','LineWidth',2);
hold on 
ha = jbfill(NEEMIPG(72:146,1)',(NEEMIPG(72:146,2)+2*NEEMIPG(72:146,3))',(NEEMIPG(72:146,2)-2*NEEMIPG(72:146,3))',[0.8500 0.3250 0.0980]);
hold on
plot(NEEMIPG(72:146,1),NEEMIPG(72:146,2),'k-','LineWidth',2);
hold on 
%Plot GISP2 data 
hb = jbfill(GISP2IPG(:,1)',(GISP2IPG(:,2)+2*GISP2IPG(:,3))',(GISP2IPG(:,2)-2*GISP2IPG(:,3))',[0.3010 0.7450 0.9330]);
hold on
plot(GISP2IPG(:,1),GISP2IPG(:,2),'k-','LineWidth',2);
hold on 
%yline(10.99,'k')
hold on
%xline(11500,'k')
hold on
%Modify graph appearance
plot([10000 30000],[0 0],'k--')
ylabel('rIPD (%)','FontSize',15)
set(gca,'XTick',[])
set(gca,'FontSize',15)
axis([11500 27300 -4.5 11])
yticks([-2 0 2 4 6 8])
%legend ([ha hb],'NEEM rIPD','GISP2 rIPD','FontSize',13,'EdgeColor','none','Color','none','Location','northwest');
hold on
yyaxis right
set (ax,'Xdir','reverse','YMinorTick','off','YColor','k')
%set(gca,'FontSize',15)
x(1) = plot (Inso(:,1)*1000,Inso(:,2),'Color','k','LineWidth',0.75);
hold on
x(2) = plot (Inso(:,1)*1000,Inso(:,12),'Color','k','LineWidth',0.75,'LineStyle','--');
hold on
axis([11500 27300 400 540])
yticks([460 480 500 520])
rp = ylabel(['Ins. (W m^-^2)'],'FontSize',15,'Color','k');
rp.Position(2) = 490;
ax.XColor = 'None';
hold on

%Plot CH4 concentrations:
box off
axes('Position',[.14, .63, .72, .2])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
yyaxis right
hold on
fa = plot(NEEMCH4(:,1),NEEMCH4(:,2),'-','Marker','.','Color',[0.8500 0.3250 0.0980],'MarkerSize',2);
hold on
fb = plot(NEEMWAISCH4(:,1),NEEMWAISCH4(:,2),'-','Marker','.','Color','#77AC30','MarkerSize',2);
hold on
fc = plot(GISP2CH4(:,1),GISP2CH4(:,2),'-','Marker','.','Color',[0.3010 0.7450 0.9330],'MarkerSize',2);
hold on
plot(GISP2WAISCH4(:,1),GISP2WAISCH4(:,2),'-','Marker','.','Color','#77AC30','MarkerSize',2);
hold on
%Label DO and Heinrich Events
text (12550,560,'YD','FontSize',18);
hold on
text (14000,560,'BA','FontSize',18);
hold on
text (16700,550,'HS1','FontSize',18);
hold on
text (23700,580,'DO2','FontSize',18);
hold on
text (26200,500,'HS2b','FontSize',18);
hold on
text (24400,500,'HS2a','FontSize',18);
hold on
%xline(27299,'k')
hold on
ylabel('[CH_4] (ppb)','FontSize',15)
set(gca,'FontSize',15)
%axis([starttime endtime CH4lower CH4upper])
axis([11500 27300 350 710])
ax.XColor = 'None';
ax.YColor = 'k';
yyaxis left
ax.YColor = 'None';
ax.XColor = 'None';
%aa = legend([fa fc fb], 'NEEM (corrected)','GISP2 (corrected)','WAIS','WAIS smooth','FontSize',13,'EdgeColor','none','Color','none','Location','northwest');
%alpha(aa,.1)

%Plot NH annd SH speleothem record
box off
axes('Position',[.14, .44, .72, .21])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
hold on
set (ax,'Xcolor','none','Xdir','reverse','YMinorTick','off','Ydir','reverse')
set(gca,'FontSize',15)
hold on
%Add shading for H and DO intervals
x(3) = plot (SpelN(:,1),SpelN(:,2),'Color',[0.4940 0.1840 0.5560],'LineWidth',1.5,'LineStyle','-');
hold on 
x(4) = plot (SpelS(1:330,2),SpelS(1:330,4),'Color',[0.8500 0.3250 0.0980],'LineWidth',1.5,'LineStyle','-');
hold on
% x(5) = plot (SpelND(:,1)/1000,SpelND(:,2),'Color',[0.6350 0.0780 0.1840],'LineStyle','-','LineWidth',1.5);
% hold on
axis([11500/1000 27300/1000 -11 -1.7])
yticks([-10 -8 -6 -4 -2 ])
%xline(11.5,'k')
lp = ylabel(['{\delta}^1^8O (' char(8240) ,')'],'FontSize',15);% '^1^8O'char(8240)],'FontSize',15)

%legend(x([1 3 4]),'Insolation','Dongge','Hulu','FontSize',13,'EdgeColor','none','Color','none','Location','northwest');%,'Baumgartner N','Baumgartner T');

%Plot GMSL and Sea Level model
box off
axes('Position',[.14, .3, .72, .16])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
hold on
yyaxis right
%plot individual sea level proxies
%scatter (SL(:,3),SL(:,4),'k')
errorbar (SL(:,3),SL(:,4),SL(:,5),'o','Color','k','MarkerSize',2,'CapSize',2,'LineWidth',.2)
hold on
jbfill(SLC(:,1)',(SLChigh+5)',(SLClow+5)',[0.9 0.9 0.9],'k');
hold on
plot (SLC(:,1),(SLChigh+5),'LineWidth',.5,'Color','k','LineStyle','-')
hold on 
plot (SLC(:,1),(SLClow+5),'LineWidth',.5,'Color','k','LineStyle','-')
hold on 
plot (SLC(:,1),(SLC(:,3)+5),'LineWidth',1,'Color','k','LineStyle','-','Marker','none')
hold on 
%xline(11.5,'k')
hold on
axis([11500/1000 27300/1000 -160 -30])
%xline(27.3,'k')
hold on
ax.XColor = 'None';
ax.YColor = 'k';
set(gca,'FontSize',15)
ylabel('GMSL (m)','FontSize',15)
yyaxis left
ax.YColor = 'None';

%Plot DeltaEland data

% box off
% axes('Position',[.11, .35, .78, .13])
% set(gca,'Color','None')
% ax = gca;
% set (ax,'Xdir','reverse')
% set (ax,'Ydir','reverse')
% hold on
% plot (Eland(:,1),Eland(:,2),edge,'Color',[0.6350 0.0780 0.1840],'LineWidth',1.5)
% ylabel(['{\Delta}', '{\epsilon}','_L_A_N_D (' char(8240) ,')_a_t_m'],'FontSize',15);
% xlim ([11.5 27.3])
% set(gca,'FontSize',15)
% ax.XColor = 'None';
% ax.YColor = 'k';

%Plot 3 box model output
box off
axes('Position',[.14, .07, .72, .26])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse','YMinorTick','on')
hold on
set(ax,'YMinorTick','on')

%Plot shading for source estimates
h(5) = jbfill(NEEMTSource(10:25,1)'/1000,(NEEMTSource(10:25,2)-2*NEEMTSource(10:25,5))',(NEEMTSource(10:25,2)+2*NEEMTSource(10:25,5))',[0.4660 0.6740 0.1880],'none');
hold on
h(5) = jbfill(NEEMTSource(34:63,1)'/1000,(NEEMTSource(34:63,2)-2*NEEMTSource(34:63,5))',(NEEMTSource(34:63,2)+2*NEEMTSource(34:63,5))',[0.4660 0.6740 0.1880],'none');
hold on
h(5) = jbfill(NEEMTSource(71:146,1)'/1000,(NEEMTSource(71:146,2)-2*NEEMTSource(71:146,5))',(NEEMTSource(71:146,2)+2*NEEMTSource(71:146,5))',[0.4660 0.6740 0.1880],'none');
hold on
h(1) = jbfill(NEEMNSource(10:25,1)'/1000,(NEEMNSource(10:25,2)-2*NEEMNSource(10:25,5))',(NEEMNSource(10:25,2)+2*NEEMNSource(10:25,5))',[0 0.4470 0.7410],'none');
hold on
h(1) = jbfill(NEEMNSource(34:63,1)'/1000,(NEEMNSource(34:63,2)-2*NEEMNSource(34:63,5))',(NEEMNSource(34:63,2)+2*NEEMNSource(34:63,5))',[0 0.4470 0.7410],'none');
hold on
h(1) = jbfill(NEEMNSource(71:146,1)'/1000,(NEEMNSource(71:146,2)-2*NEEMNSource(71:146,5))',(NEEMNSource(71:146,2)+2*NEEMNSource(71:146,5))',[0 0.4470 0.7410],'none');
hold on
h(3) = jbfill(GISP2NSource(3:251,1)'/1000,(GISP2NSource(3:251,2)-2*GISP2NSource(3:251,5))',(GISP2NSource(3:251,2)+2*GISP2NSource(3:251,5))',[0 0.4470 0.7410],'none');
hold on
h(7) = jbfill(GISP2TSource(3:251,1)'/1000,(GISP2TSource(3:251,2)-2*GISP2TSource(3:251,5))',(GISP2TSource(3:251,2)+2*GISP2TSource(3:251,5))',[0.4660 0.6740 0.1880],'none');
hold on

%plot uncertainty lines on N source
plot (GISP2NSource(3:251,1)/1000,(GISP2NSource(3:251,2)-2*GISP2NSource(3:251,5)),'-','Color',[0.3 0.3 0.3])
hold on 
plot (GISP2NSource(3:251,1)/1000,(GISP2NSource(3:251,2)+2*GISP2NSource(3:251,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMNSource(10:25,1)/1000,(NEEMNSource(10:25,2)-2*NEEMNSource(10:25,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMNSource(34:63,1)/1000,(NEEMNSource(34:63,2)-2*NEEMNSource(34:63,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMNSource(71:146,1)/1000,(NEEMNSource(71:146,2)-2*NEEMNSource(71:146,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMNSource(10:25,1)/1000,(NEEMNSource(10:25,2)+2*NEEMNSource(10:25,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMNSource(34:63,1)/1000,(NEEMNSource(34:63,2)+2*NEEMNSource(34:63,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMNSource(71:146,1)/1000,(NEEMNSource(71:146,2)+2*NEEMNSource(71:146,5)),'-','Color',[0.3 0.3 0.3])
hold on
%plot uncertainty lines on T source
plot (GISP2TSource(3:251,1)/1000,(GISP2TSource(3:251,2)-2*GISP2TSource(3:251,5)),'-','Color',[0.3 0.3 0.3])
hold on 
plot (GISP2TSource(3:251,1)/1000,(GISP2TSource(3:251,2)+2*GISP2TSource(3:251,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMTSource(10:25,1)/1000,(NEEMTSource(10:25,2)-2*NEEMTSource(10:25,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMTSource(34:63,1)/1000,(NEEMTSource(34:63,2)-2*NEEMTSource(34:63,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMTSource(71:146,1)/1000,(NEEMTSource(71:146,2)-2*NEEMTSource(71:146,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMTSource(10:25,1)/1000,(NEEMTSource(10:25,2)+2*NEEMTSource(10:25,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMTSource(34:63,1)/1000,(NEEMTSource(34:63,2)+2*NEEMTSource(34:63,5)),'-','Color',[0.3 0.3 0.3])
hold on
plot (NEEMTSource(71:146,1)/1000,(NEEMTSource(71:146,2)+2*NEEMTSource(71:146,5)),'-','Color',[0.3 0.3 0.3])
hold on

%Plot mean source estimates
h(6) = plot(NEEMTSource(10:25,1)/1000,NEEMTSource(10:25,2),'k-','LineWidth',2);
hold on
h(6) = plot(NEEMTSource(34:63,1)/1000,NEEMTSource(34:63,2),'k-','LineWidth',2);
hold on
h(6) = plot(NEEMTSource(71:146,1)/1000,NEEMTSource(71:146,2),'k-','LineWidth',2);
hold on
h(8) = plot(GISP2TSource(3:251,1)/1000,GISP2TSource(3:251,2),'k-','LineWidth',2);
hold on
h(2) = plot(NEEMNSource(10:25,1)/1000,NEEMNSource(10:25,2),'k-','LineWidth',2);
hold on
h(2) = plot(NEEMNSource(34:63,1)/1000,NEEMNSource(34:63,2),'k-','LineWidth',2);
hold on
h(2) = plot(NEEMNSource(71:146,1)/1000,NEEMNSource(71:146,2),'k-','LineWidth',2);
hold on
h(4) = plot(GISP2NSource(3:251,1)/1000,GISP2NSource(3:251,2),'k-','LineWidth',2);
hold on

%Plot Southern source estimate:
h(9) = plot(NEEMSSource(:,1)/1000,NEEMSSource(:,2),'-','LineWidth',2,'Color',[0.9290 0.6940 0.1250]);
h(10) = plot(GISP2SSource(:,1)/1000,(GISP2SSource(:,2)),'-','LineWidth',2,'Color',[0.9290 0.6940 0.1250]);
hold on
ylabel('Source (Tg yr^-^1)','FontSize',15)
%xlabel ('Age (kyr)','FontSize',15)
set(gca,'FontSize',15)
legend(h([1 5 9]),'N source','T source','S source','FontSize',13,'EdgeColor','none','Color','none','Location','northwest');%,'Baumgartner N','Baumgartner T');
axis([11500/1000 27300/1000 -5 150])
hold on
xlabel('Age (kyr)','FontSize',15)
%xline(11.5,'k')
hold on
ax.YColor = 'k';
ax.XColor = 'k';


annotation('textbox',[.013 .88 .1 .1],'String','(a)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.93 .74 .1 .1],'String','(b)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.013 .54 .1 .1],'String','(c)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
%annotation('textbox',[.96 .51 .1 .1],'String','D','EdgeColor','none','FontSize',23,'FontWeight','bold','Color',[.3 .3 .3])
annotation('textbox',[.93 .38 .1 .1],'String','(d)','EdgeColor','none' ,'FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.013 .23 .1 .1],'String','(e)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
%annotation('textbox',[.94 .29 .1 .1],'String','(F)','EdgeColor','none' ,'FontSize',20,'FontWeight','bold','Color','k')
