%This code takes the output from GISP2_and_NEEMrIPD to generate several
%figures that display the NEEM and GISP2 derived rIPDs.

%Code generated by Ben Riddell-Young (January 2021)

close all
%clear all

%% Load data from GISP2_and_NEEMrIPD.mat 

gradient = load(['gradient.mat']);
gradient = gradient.gradient;
j = 11; %Desired level of smoothing tos  be plotted

%Load uncorrected NEEM
NEEMCH4_u = cell2mat(gradient(1,1));
NEEMWAIS_u = cell2mat(gradient(1,2)); 
NEEMTieAge = cell2mat(gradient(1,3));
NEEMIPG_u = cell2mat(gradient(1,4));
NEEM_IA_u = cell2mat(gradient(1,5));
%Load uncorrected GISP2
GISP2CH4_u = cell2mat(gradient(1,6));
GISP2WAIS_u = cell2mat(gradient(1,7));
GISP2TieAge = cell2mat(gradient(1,8));
GISP2IPG_u = cell2mat(gradient(1,9));
GISP2_IA_u = cell2mat(gradient(1,10));
%Load corrected NEEM
NEEMCH4_c = cell2mat(gradient(2,1));
NEEMWAIS_c = cell2mat(gradient(2,2)); 
NEEMIPG_c = cell2mat(gradient(2,4));
NEEM_IA_c = cell2mat(gradient(2,5));
%Load corrected GISP2
GISP2CH4_c = cell2mat(gradient(2,6));
GISP2WAIS_c = cell2mat(gradient(2,7));
GISP2IPG_c = cell2mat(gradient(2,9));
GISP2_IA_c = cell2mat(gradient(2,10));

%Load WDC CFA data
CFA = xlsread('Rhodes_CFA.xlsx');   %Rhodes et al., 2015
CFA_Depth = CFA(:,1);
CFA_GasAge = CFA(:,5);
CFA_CH4 = CFA(:,4);

%Load NEEM Ca2+ data
NEEMCaData = csvread('NEEM_CH4_Ca2+_data 2.csv',9,0);
    NEEMCaDepth = NEEMCaData(:,2);
    NEEMCa2 = NEEMCaData(:,3);
NaNaa = find(isnan(NEEMCa2));
NEEMCa2(NaNaa) = [];
NEEMCaDepth(NaNaa) = [];
%Intertpolate
NEEMCa2gasage = interp1(NEEMCH4_c(:,3),NEEMCH4_c(:,1),NEEMCaDepth);

%New as of July 2023
%Load GISP2 Ca2+ data 
GISP2_Data=csvread('gisp2_ca2plus_july23.csv',2,0);
load('G2_MatchForced_Timescale_TEMP_20201017.mat');
GISP2depth = g2_updated_timescale(:,1);
GISP2iceage = g2_updated_timescale(:,2);
GISP2gasage = g2_updated_timescale(:,3);
GISP2_depth_ca2plus = GISP2_Data(:,1);
GISP2_Ca2plus = GISP2_Data(:,2);
GISP2Ca2gasage = interp1(GISP2depth,GISP2gasage,GISP2_depth_ca2plus);

%% %% Load Previous interval average data
% %        AgeM  dur  mean std
Brook = [10500 2000 6.2 0.8;
         12000 1000 3.9 1;
         14150 1300 3.2 1;
         22000 8000 4.8 1.4];

Baumgartner = [12078 742 5.6 0.8;
               13339 792 6.6 1.0;
               14044 617 6.8 0.9;
               16254 3099 7.6 1.6;
               19109 2611 6.1 0.5;
               21545 656 3.7 0.7;
               22605 984 7.1 0.5;
               25672 2568 5.0 0.8];
           
Dallenbach = [12065 870 5.7 2.0;
              13600 1800 4.1 1.6;
              18500 3600 -0.8 1.1];

Chappellaz = [10500 2000 6.9 1.1];
     
%% Define x lims for climate intervals

%Timing of DO events obtained from Rasmussen et al., 2014 GICC05 chronology
%Timing of Heinrich events obtained from chapman et al., 1999 on the GICC05 chronology

BAx = [14550 12800 12800 14550];
H1x = [17700 14600 14600 17700];
DOx = [23350 22900 22900 23350];
H2bx = [24000 23430 23430 24000];
H2ax = [25725 25100 25100 25725];

%% Plot GISP2 and NEEM rIPD records 
%Plot only desired result:
f = figure(3);
f.Position = [100 100 1100 750];
hold on
set(gcf,'Color','w');
ax = gca;
ax.XColor = 'None';
ax.YColor = 'None';
clear ax
%Plot data with desired smoothing:
%Load NEEM and GISP2 Ca2+ data and plot on secondary axis
% NEEMCaData = csvread('NEEM_CH4_Ca2+_data 2.csv',9,0);
%     NEEMCaDepth = NEEMCaData(:,2);
%     NEEMCa2 = NEEMCaData(:,3);
% NaNaa = find(isnan(NEEMCa2));
% NEEMCa2(NaNaa) = [];
% NEEMCaDepth(NaNaa) = [];
% %Intertpolate
% NEEMCa2gasage = interp1(NEEMCH4_c(:,3),NEEMCH4_c(:,1),NEEMCaDepth);

%plot
%subplot(4,1,1)
box off
axes('Position',[.56, .67, .37, .30])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
hold on
hb = plot(NEEMCH4_c(:,1),NEEMCH4_c(:,2),'color','#0072BD','LineStyle','-','Marker','.','MarkerSize',1);
hold on 
hbb = plot(NEEMCH4_u(:,1),NEEMCH4_u(:,2),'color','#A2142F','LineStyle','-','Marker','.','MarkerSize',1);
hold on
hc = plot(NEEMWAIS_c(:,1),NEEMWAIS_c(:,2),'color','#77AC30','LineStyle','-','Marker','.','MarkerSize',1);
hold on 
hd = plot(CFA_GasAge,CFA_CH4,'color','k','LineStyle','-','LineWidth',.75);
hold on
he = plot(NEEMTieAge,800*ones(length(NEEMTieAge),1),'vk','MarkerFaceColor','k','MarkerSize',2);
axis([10100 18610 325 800])
%set(gca,'XGrid','on','YGrid','on')
%str1={'Smoothing = ', num2str(j*10*5), 'years'}
%title(str1)
%ylabel('CH_4 (ppb)','FontSize',15)
set(gca,'FontSize',15)
%Label DO and Heinrich Events
text (13900,550,'BA','FontSize',18);
hold on
text (16500,530,'HS1','FontSize',18);
hold on
text (12400,550,'YD','FontSize',18);
hold on
legend([hb hbb hc hd he],'NEEM Corrected','NEEM Unorrected','WAIS Divide','WAIS Divide CFA','NEEM tie points','EdgeColor','none','Color','none','FontSize',13,'Location',[.5925, .83, .1, .1])
ax.XColor = 'None';
ax.YColor = 'k';
set(gca,'YTickLabel', [])

%Plot Ca2+ data
box off
axes('Position',[.56, .57, .37, .19])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
yyaxis right
hold on
plot (NEEMCa2gasage(1:10000),NEEMCa2(1:10000),'color',[0.8500 0.3250 0.0980]);
hold on
%Add shading for DO and Heinrich events
ylabel ('[Ca^2^+] (ng/g)','FontSize',15)
set(gca,'FontSize',15)
axis ([10100 18610 0 1100])
%legend ('NEEM Ca^2^+','EdgeColor','none','Color','none','FontSize',13,'Location','northeast');
set (ax,'Xdir','reverse')
ax.XColor = 'None';
ax.YColor = 'k';
yyaxis left
ax.YColor = 'None';

%Plot absolute IPD (not including abrupt transitions)
box off
axes('Position',[.56, .40, .37, .19])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
colororder({'w','k'})
hold on
plot (NEEMIPG_c(12:24,1),NEEMIPG_c(12:24,32),'color','b','LineWidth',1.5);
hold on
plot (NEEMIPG_c(35:62,1),NEEMIPG_c(35:62,32),'color','b','LineWidth',1.5);
hold on
plot (NEEMIPG_c(72:end,1),NEEMIPG_c(72:end,32),'color','b','LineWidth',1.5);
hold on
plot (NEEMIPG_u(12:24,1),NEEMIPG_u(12:24,32),'color','r','LineWidth',1.5);
hold on
plot (NEEMIPG_u(35:62,1),NEEMIPG_u(35:62,32),'color','r','LineWidth',1.5);
hold on
plot (NEEMIPG_u(72:end,1),NEEMIPG_u(72:end,32),'color','r','LineWidth',1.5);
hold on
yline(0,'k--')
hold on
%ylabel ('CH_4 IPD: C_N - C_S (ppb)','FontSize',15)
set(gca,'FontSize',15)
axis ([10100 18610 -10 40])
%legend ('NEEM Ca^2^+','EdgeColor','none','Color','none','FontSize',13,'Location','northeast');
set (ax,'Xdir','reverse')
ax.XColor = 'None';
set(gca,'YTickLabel', [])
ax.YColor = 'k';

%Plot continuous IPD with desired smoothing:
box off
axes('Position',[.56, .07, .37, .38])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
hold on
yyaxis right
Brookbars=[(Brook(:,1)-0.5*Brook(:,2)) (Brook(:,1)+0.5*Brook(:,2))];
for i=1:3
    errorbar(Brook(i,1)/1000,Brook(i,3),Brook(i,4),'gs','Markersize',4,'linewidth',2)
    ha = plot([Brookbars(i,1)/1000 Brookbars(i,2)/1000],Brook(i,3)*ones(2,1),'g-','linewidth',2);       
end
% %Next, Dallenbach et al, 2000.
Dallenbachbars=[(Dallenbach(:,1)-0.5*Dallenbach(:,2)) (Dallenbach(:,1)+0.5*Dallenbach(:,2))];
for i=1:3
    errorbar(Dallenbach(i,1)/1000,Dallenbach(i,3),Dallenbach(i,4),'ms','Markersize',4,'linewidth',2)
    hb = plot([Dallenbachbars(i,1)/1000 Dallenbachbars(i,2)/1000],Dallenbach(i,3)*ones(2,1),'m-','linewidth',2);       
end
% %Next, Baumgartner et al, 2012
Baumgartnerbars=[(Baumgartner(:,1)-0.5*Baumgartner(:,2)) (Baumgartner(:,1)+0.5*Baumgartner(:,2))];
for i=1:8
    errorbar(Baumgartner(i,1)/1000,Baumgartner(i,3),Baumgartner(i,4),'ks','Markersize',4,'linewidth',2)
    hc = plot([Baumgartnerbars(i,1)/1000 Baumgartnerbars(i,2)/1000],Baumgartner(i,3)*ones(2,1),'k-','linewidth',2);       
end
hold on

% %Next, Chappellaz et al., 1997
Chappellazbars=[(Chappellaz(:,1)-0.5*Chappellaz(:,2)) (Chappellaz(:,1)+0.5*Chappellaz(:,2))];
for i=1:1
    errorbar(Chappellaz(i,1)/1000,Chappellaz(i,3),Chappellaz(i,4),'color',"#7E2F8E",'Marker','s','Markersize',4,'linewidth',2)
    hc = plot([Chappellazbars(i,1)/1000 Chappellazbars(i,2)/1000],Chappellaz(i,3)*ones(2,1),'color',"#7E2F8E",'LineStyle','-','linewidth',2);       
end
hold on
%%%%%%%%%Plot interval-averages of continuous IPD:
% %NEEM Uncorrected
% plotbars=[NEEM_IA_u(:,1)-0.5*NEEM_IA_u(:,2) NEEM_IA_u(:,1)+0.5*NEEM_IA_u(:,2)];
% for i=1:4
%     errorbar(NEEM_IA_u(i,1),NEEM_IA_u(i,(j+1)),NEEM_IA_u(i,(j+17)),'bs','Markersize',8,'linewidth',2)
%     plot([plotbars(i,1) plotbars(i,2)],NEEM_IA_u(i,11)*ones(2,1),'b','linewidth',2)       
% end
% hold on 
% %NEEM Corrected
% plotbars=[NEEM_IA_c(:,1)-0.5*NEEM_IA_c(:,2) NEEM_IA_c(:,1)+0.5*NEEM_IA_c(:,2)];
% for i=1:4
%     errorbar(NEEM_IA_c(i,1),NEEM_IA_c(i,(j+1)),NEEM_IA_c(i,(j+17)),'bs','Markersize',8,'linewidth',2)
%     plot([plotbars(i,1) plotbars(i,2)],NEEM_IA_c(i,11)*ones(2,1),'b','linewidth',2)       
% end
% hold on 
% %GISP2 Uncorrected
% plotbars=[GISP2_IA_u(:,1)-0.5*GISP2_IA_u(:,2) GISP2_IA_u(:,1)+0.5*GISP2_IA_u(:,2)];
% for i=1:4
%     errorbar(GISP2_IA_u(i,1),GISP2_IA_u(i,(j+1)),GISP2_IA_u(i,(j+17)),'bs','Markersize',8,'linewidth',2)
%     plot([plotbars(i,1) plotbars(i,2)],GISP2_IA_u(i,11)*ones(2,1),'b','linewidth',2)       
% end
% hold on 
% %GISP2 Corrected
% plotbars=[GISP2_IA_c(:,1)-0.5*GISP2_IA_c(:,2) GISP2_IA_c(:,1)+0.5*GISP2_IA_c(:,2)];
% for i=1:4
%     errorbar(GISP2_IA_c(i,1),GISP2_IA_c(i,(j+1)),GISP2_IA_c(i,(j+17)),'bs','Markersize',8,'linewidth',2)
%     plot([plotbars(i,1) plotbars(i,2)],GISP2_IA_c(i,11)*ones(2,1),'b','linewidth',2)       
% end
% hold on 

%%%%%%%%% Plot Continuous IPD:
%Plot uncorrected NEEM
%YD interval
plot(NEEMIPG_u(12:24,1)/1000,NEEMIPG_u(12:24,(j+1)),'r-','LineWidth',2);
hold on
plot(NEEMIPG_u(12:24,1)/1000,(NEEMIPG_u(12:24,(j+1))+2*NEEMIPG_u(12:24,(j+16))),'k-');
hold on
plot(NEEMIPG_u(12:24,1)/1000,(NEEMIPG_u(12:24,(j+1))-2*NEEMIPG_u(12:24,(j+16))),'k-');
hold on
hdd = jbfill(NEEMIPG_u(12:24,1)'/1000,(NEEMIPG_u(12:24,(j+1))+2*NEEMIPG_u(12:24,(j+16)))',(NEEMIPG_u(12:24,(j+1))-2*NEEMIPG_u(12:24,(j+16)))',[0.6350 0.0780 0.1840],'none');
hold on 
%BA interval
plot(NEEMIPG_u(35:62,1)/1000,NEEMIPG_u(35:62,(j+1)),'r-','LineWidth',2);
hold on
plot(NEEMIPG_u(35:62,1)/1000,(NEEMIPG_u(35:62,(j+1))+2*NEEMIPG_u(35:62,(j+16))),'k-');
hold on
plot(NEEMIPG_u(35:62,1)/1000,(NEEMIPG_u(35:62,(j+1))-2*NEEMIPG_u(35:62,(j+16))),'k-');
hold on
hdd = jbfill(NEEMIPG_u(35:62,1)'/1000,(NEEMIPG_u(35:62,(j+1))+2*NEEMIPG_u(35:62,(j+16)))',(NEEMIPG_u(35:62,(j+1))-2*NEEMIPG_u(35:62,(j+16)))',[0.6350 0.0780 0.1840],'none');
hold on 
%H1 interval
plot(NEEMIPG_u(72:146,1)/1000,NEEMIPG_u(72:146,(j+1)),'r-','LineWidth',2);
hold on
plot(NEEMIPG_u(72:146,1)/1000,(NEEMIPG_u(72:146,(j+1))+2*NEEMIPG_u(72:146,(j+16))),'k-');
hold on
plot(NEEMIPG_u(72:146,1)/1000,(NEEMIPG_u(72:146,(j+1))-2*NEEMIPG_u(72:146,(j+16))),'k-');
hold on
hdd = jbfill(NEEMIPG_u(72:146,1)'/1000,(NEEMIPG_u(72:146,(j+1))+2*NEEMIPG_u(72:146,(j+16)))',(NEEMIPG_u(72:146,(j+1))-2*NEEMIPG_u(72:146,(j+16)))',[0.6350 0.0780 0.1840],'none');
hold on 
%Plot corrected NEEM
%YD interval
plot(NEEMIPG_c(12:24,1)/1000,NEEMIPG_c(12:24,(j+1)),'b-','LineWidth',2);
hold on
plot(NEEMIPG_c(12:24,1)/1000,(NEEMIPG_c(12:24,(j+1))+2*NEEMIPG_c(12:24,(j+16))),'k-');
hold on
plot(NEEMIPG_c(12:24,1)/1000,(NEEMIPG_c(12:24,(j+1))-2*NEEMIPG_c(12:24,(j+16))),'k-');
hold on
hd = jbfill(NEEMIPG_c(12:24,1)'/1000,(NEEMIPG_c(12:24,(j+1))+2*NEEMIPG_c(12:24,(j+16)))',(NEEMIPG_c(12:24,(j+1))-2*NEEMIPG_c(12:24,(j+16)))',[0 0.4470 0.7410],'none');
hold on 
%BA interval
plot(NEEMIPG_c(35:62,1)/1000,NEEMIPG_c(35:62,(j+1)),'b-','LineWidth',2);
hold on
plot(NEEMIPG_c(35:62,1)/1000,(NEEMIPG_c(35:62,(j+1))+2*NEEMIPG_c(35:62,(j+16))),'k-');
hold on
plot(NEEMIPG_c(35:62,1)/1000,(NEEMIPG_c(35:62,(j+1))-2*NEEMIPG_c(35:62,(j+16))),'k-');
hold on
hd = jbfill(NEEMIPG_c(35:62,1)'/1000,(NEEMIPG_c(35:62,(j+1))+2*NEEMIPG_c(35:62,(j+16)))',(NEEMIPG_c(35:62,(j+1))-2*NEEMIPG_c(35:62,(j+16)))',[0 0.4470 0.7410],'none');
hold on 
%H1 interval
plot(NEEMIPG_c(72:146,1)/1000,NEEMIPG_c(72:146,(j+1)),'b-','LineWidth',2);
hold on
plot(NEEMIPG_c(72:146,1)/1000,(NEEMIPG_c(72:146,(j+1))+2*NEEMIPG_c(72:146,(j+16))),'k-');
hold on
plot(NEEMIPG_c(72:146,1)/1000,(NEEMIPG_c(72:146,(j+1))-2*NEEMIPG_c(72:146,(j+16))),'k-');
hold on
hd = jbfill(NEEMIPG_c(72:146,1)'/1000,(NEEMIPG_c(72:146,(j+1))+2*NEEMIPG_c(72:146,(j+16)))',(NEEMIPG_c(72:146,(j+1))-2*NEEMIPG_c(72:146,(j+16)))',[0 0.4470 0.7410],'none');
hold on 
ax.XColor = 'k';
ax.YColor = 'k';
ylim([-3 12])
ylabel('rIPD (C_N/C_S-1)*100','FontSize',15)
yyaxis left
ax.YColor = 'None';

%Modify graph appearance:
plot([10000 30000],[0 0],'k--')
hold off
yline(-.15,'k--')
hold on
axis([10100/1000 18610/1000 -3.3 12.5])
set(gca,'XGrid','off','YGrid','off')
xlabel('Age (kyr)','FontSize',15)
set(gca,'FontSize',15)
legend([hdd hd],'Uncorrected NEEM','Corrected NEEM','EdgeColor','none','Color','none','FontSize',13,'Location',[.81, .38, .02, .02])
annotation('textbox',[.5575 .87 .1 .1],'String','(e)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.885 .66 .1 .1],'String','(f)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.5575 .49 .1 .1],'String','(g)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.885 .345 .1 .1],'String','(h)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
%Add shading for HS and DO intervals
annotation('rectangle',[.6025 .07 .13 .90],'FaceColor',[0 0.4470 0.7410],'FaceAlpha',.1,'EdgeColor','none')
annotation('rectangle',[.735 .07 .0775 .90],'FaceColor','k','FaceAlpha',.1,'EdgeColor','none')


% Now plot GISP2 record

%Plot only desired result:
% f = figure(2);
% f.Position = [100 100 800 750];
% hold on
% set(gcf,'Color','w');
% ax = gca;
% ax.XColor = 'None';
% ax.YColor = 'None';
% clear ax
%Plot data with desired smoothing:
%Load NEEM and GISP2 Ca2+ data and plot on secondary axis
% NEEMCaData = csvread('NEEM_CH4_Ca2+_data 2.csv',9,0);
%     NEEMCaDepth = NEEMCaData(:,2);
%     NEEMCa2 = NEEMCaData(:,3);
% NaNaa = find(isnan(NEEMCa2));
% NEEMCa2(NaNaa) = [];
% NEEMCaDepth(NaNaa) = [];
% %Intertpolate
% NEEMCa2gasage = interp1(NEEMCH4_c(:,3),NEEMCH4_c(:,1),NEEMCaDepth);

%plot
%subplot(4,1,1)
box off
axes('Position',[.06, .67, .48, .30])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
hold on
hb = plot(GISP2CH4_c(:,1),GISP2CH4_c(:,2),'color','#0072BD','LineStyle','-','Marker','.','MarkerSize',1);
hold on 
hbb = plot(GISP2CH4_u(:,1),GISP2CH4_u(:,2),'color','#A2142F','LineStyle','-','Marker','.','MarkerSize',1);
hold on
hc = plot(GISP2WAIS_c(:,1),GISP2WAIS_c(:,2),'color','#77AC30','LineStyle','-','Marker','.','MarkerSize',1);
hold on 
hd = plot(CFA_GasAge,CFA_CH4,'color','k','LineStyle','-','LineWidth',.75);
hold on
he = plot(GISP2TieAge,800*ones(length(GISP2TieAge),1),'vk','MarkerFaceColor','k','MarkerSize',2);
axis([14740 27500 325 800])
%set(gca,'XGrid','on','YGrid','on')
%str1={'Smoothing = ', num2str(j*10*5), 'years'}
%title(str1)
ylabel('CH_4 (ppb)','FontSize',15)
set(gca,'FontSize',15)
%Label DO and Heinrich Events
text (16500,550,'HS1','FontSize',18);
hold on
text (23550,550,'DO2','FontSize',18);
hold on
text (26050,500,'HS2b','FontSize',18);
hold on
text (24250,500,'HS2a','FontSize',18);
hold on
legend([hb hbb hc hd he],'GISP2 Corrected','GISP2 Unorrected','WAIS Divide','WAIS Divide CFA','GISP2 tie points','EdgeColor','none','Color','none','FontSize',13,'Location',[.095, .825, .1, .1])
ax.XColor = 'None';
ax.YColor = 'k';

box off
axes('Position',[.06, .57, .48, .19])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
yyaxis right
hold on
%plot (GISP2Ca2gasage(1:10000),GISP2Ca2(1:10000),'color',[0.8500 0.3250 0.0980]);
plot (GISP2Ca2gasage,GISP2_Ca2plus,'color',[0.8500 0.3250 0.0980]);
hold on
%Add shading for DO and Heinrich events
%ylabel ('[Ca^2^+] (ng/g)','FontSize',15)
set(gca,'FontSize',15)
axis ([14740 27500 0 1100])
%legend ('NEEM Ca^2^+','EdgeColor','none','Color','none','FontSize',13,'Location','northeast');
set (ax,'Xdir','reverse')
ax.XColor = 'None';
ax.YColor = 'k';
set(gca,'YTickLabel', [])
yyaxis left
ax.YColor = 'None';

%Plot absolute IPD (not including abrupt transitions)
box off
axes('Position',[.06, .40, .48, .19])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
colororder({'w','k'})
hold on
plot (GISP2IPG_c(:,1),GISP2IPG_c(:,32),'color','b','LineWidth',1.5);
hold on
plot (GISP2IPG_u(:,1),GISP2IPG_u(:,32),'color','r','LineWidth',1.5);
hold on
yline(0,'k--')
hold on
ylabel ('CH_4 IPD: C_N - C_S (ppb)','FontSize',15)
set(gca,'FontSize',15)
axis ([14740 27500 -10 40])
%legend ('NEEM Ca^2^+','EdgeColor','none','Color','none','FontSize',13,'Location','northeast');
set (ax,'Xdir','reverse')
ax.XColor = 'None';
ax.YColor = 'k';

%Plot continuous IPD with desired smoothing:
box off
axes('Position',[.06, .07, .48, .38])
set(gca,'Color','None')
ax = gca;
set (ax,'Xdir','reverse')
hold on
yyaxis right
Brookbars=[(Brook(:,1)-0.5*Brook(:,2)) (Brook(:,1)+0.5*Brook(:,2))];
for i=1:3
    errorbar(Brook(i,1)/1000,Brook(i,3),Brook(i,4),'gs','Markersize',4,'linewidth',2)
    ha = plot([Brookbars(i,1)/1000 Brookbars(i,2)/1000],Brook(i,3)*ones(2,1),'g-','linewidth',2);       
end
% %Next, Dallenbach et al, 2000.
Dallenbachbars=[(Dallenbach(:,1)-0.5*Dallenbach(:,2)) (Dallenbach(:,1)+0.5*Dallenbach(:,2))];
for i=1:3
    errorbar(Dallenbach(i,1)/1000,Dallenbach(i,3),Dallenbach(i,4),'ms','Markersize',4,'linewidth',2)
    hb = plot([Dallenbachbars(i,1)/1000 Dallenbachbars(i,2)/1000],Dallenbach(i,3)*ones(2,1),'m-','linewidth',2);       
end
% %Next, Baumgartner et al, 2012
Baumgartnerbars=[(Baumgartner(:,1)-0.5*Baumgartner(:,2)) (Baumgartner(:,1)+0.5*Baumgartner(:,2))];
for i=1:8
    errorbar(Baumgartner(i,1)/1000,Baumgartner(i,3),Baumgartner(i,4),'ks','Markersize',4,'linewidth',2)
    hc = plot([Baumgartnerbars(i,1)/1000 Baumgartnerbars(i,2)/1000],Baumgartner(i,3)*ones(2,1),'k-','linewidth',2);       
end
hold on

% % %Next, Chappellaz et al., 1997
% Chappellazbars=[(Chappellaz(:,1)-0.5*Chappellaz(:,2)) (Chappellaz(:,1)+0.5*Chappellaz(:,2))];
% for i=1:1
%     errorbar(Chappellaz(i,1)/1000,Chappellaz(i,3),Chappellaz(i,4),'color',"#7E2F8E",'Marker','s','Markersize',8,'linewidth',2)
%     hc = plot([Chappellazbars(i,1)/1000 Chappellazbars(i,2)/1000],Chappellaz(i,3)*ones(2,1),'color',"#7E2F8E",'LineStyle','-','linewidth',2);       
% end
% hold on
%%%%%%%%%Plot interval-averages of continuous IPD:
% %NEEM Uncorrected
% plotbars=[NEEM_IA_u(:,1)-0.5*NEEM_IA_u(:,2) NEEM_IA_u(:,1)+0.5*NEEM_IA_u(:,2)];
% for i=1:4
%     errorbar(NEEM_IA_u(i,1),NEEM_IA_u(i,(j+1)),NEEM_IA_u(i,(j+17)),'bs','Markersize',8,'linewidth',2)
%     plot([plotbars(i,1) plotbars(i,2)],NEEM_IA_u(i,11)*ones(2,1),'b','linewidth',2)       
% end
% hold on 
% %NEEM Corrected
% plotbars=[NEEM_IA_c(:,1)-0.5*NEEM_IA_c(:,2) NEEM_IA_c(:,1)+0.5*NEEM_IA_c(:,2)];
% for i=1:4
%     errorbar(NEEM_IA_c(i,1),NEEM_IA_c(i,(j+1)),NEEM_IA_c(i,(j+17)),'bs','Markersize',8,'linewidth',2)
%     plot([plotbars(i,1) plotbars(i,2)],NEEM_IA_c(i,11)*ones(2,1),'b','linewidth',2)       
% end
% hold on 
% %GISP2 Uncorrected
% plotbars=[GISP2_IA_u(:,1)-0.5*GISP2_IA_u(:,2) GISP2_IA_u(:,1)+0.5*GISP2_IA_u(:,2)];
% for i=1:4
%     errorbar(GISP2_IA_u(i,1),GISP2_IA_u(i,(j+1)),GISP2_IA_u(i,(j+17)),'bs','Markersize',8,'linewidth',2)
%     plot([plotbars(i,1) plotbars(i,2)],GISP2_IA_u(i,11)*ones(2,1),'b','linewidth',2)       
% end
% hold on 
% %GISP2 Corrected
% plotbars=[GISP2_IA_c(:,1)-0.5*GISP2_IA_c(:,2) GISP2_IA_c(:,1)+0.5*GISP2_IA_c(:,2)];
% for i=1:4
%     errorbar(GISP2_IA_c(i,1),GISP2_IA_c(i,(j+1)),GISP2_IA_c(i,(j+17)),'bs','Markersize',8,'linewidth',2)
%     plot([plotbars(i,1) plotbars(i,2)],GISP2_IA_c(i,11)*ones(2,1),'b','linewidth',2)       
% end
% hold on 

%%%%%%%%% Plot Continuous IPD:
%Plot uncorrected GISP2
plot(GISP2IPG_u(:,1)/1000,GISP2IPG_u(:,(j+1)),'r-','LineWidth',2);
hold on
plot(GISP2IPG_u(:,1)/1000,(GISP2IPG_u(:,(j+1))+2*GISP2IPG_u(:,(j+16))),'k-');
hold on
plot(GISP2IPG_u(:,1)/1000,(GISP2IPG_u(:,(j+1))-2*GISP2IPG_u(:,(j+16))),'k-');
hold on
hdd = jbfill(GISP2IPG_u(:,1)'/1000,(GISP2IPG_u(:,(j+1))+2*GISP2IPG_u(:,(j+16)))',(GISP2IPG_u(:,(j+1))-2*GISP2IPG_u(:,(j+16)))',[0.6350 0.0780 0.1840],'none');
hold on 

%Plot corrected GISP2
plot(GISP2IPG_c(:,1)/1000,GISP2IPG_c(:,(j+1)),'b-','LineWidth',2);
hold on
plot(GISP2IPG_c(:,1)/1000,(GISP2IPG_c(:,(j+1))+2*GISP2IPG_c(:,(j+16))),'k-');
hold on
plot(GISP2IPG_c(:,1)/1000,(GISP2IPG_c(:,(j+1))-2*GISP2IPG_c(:,(j+16))),'k-');
hold on
hd = jbfill(GISP2IPG_c(:,1)'/1000,(GISP2IPG_c(:,(j+1))+2*GISP2IPG_c(:,(j+16)))',(GISP2IPG_c(:,(j+1))-2*GISP2IPG_c(:,(j+16)))',[0 0.4470 0.7410],'none');
hold on 
ax.XColor = 'k';
ax.YColor = 'k';
set(gca,'YTickLabel', [])
ylim([-3 12])
yline(0,'k--')
%ylabel('rIPD (C_N/C_S-1)*100','FontSize',15)
yyaxis left
ax.YColor = 'None';


%Modify graph appearance:
hold off
hold on
axis([14740/1000 27500/1000 -3.3 12.5])
set(gca,'XGrid','off','YGrid','off')
xlabel('Age (kyr)','FontSize',15)
set(gca,'FontSize',15)
legend([hdd hd],'Uncorrected GISP2','Corrected GISP2','EdgeColor','none','Color','none','FontSize',13,'Location',[.38, .39, .02, .02])
annotation('textbox',[.06 .87 .1 .1],'String','(a)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.505 .65 .1 .1],'String','(b)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.06 .48 .1 .1],'String','(c)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
annotation('textbox',[.505 .35 .1 .1],'String','(d)','EdgeColor','none','FontSize',20,'FontWeight','bold','Color','k')
%Add shading for HS and DO intervals
annotation('rectangle',[.13 .07 .0225 .90],'FaceColor',[0 0.4470 0.7410],'FaceAlpha',.1,'EdgeColor','none')
annotation('rectangle',[.1925 .07 .0225 .90],'FaceColor',[0 0.4470 0.7410],'FaceAlpha',.1,'EdgeColor','none')
annotation('rectangle',[.2175 .07 .0175 .90],'FaceColor','k','FaceAlpha',.1,'EdgeColor','none')
annotation('rectangle',[.4275 .07 .1125 .90],'FaceColor',[0 0.4470 0.7410],'FaceAlpha',.1,'EdgeColor','none')


